version: '3.8'
services:
  senai1:
    image: "${REPO_URL}/${REPO_NAME}:${IMAGE_CONTAINERBUILD1_VERSAO}"
    ports:
      - "80:80"
      - "443:443"
    environment:
      IMAGE_CONTAINERBUILD1: ${IMAGE_CONTAINERBUILD1}
      IMAGE_CONTAINERBUILD1_URL: ${IMAGE_CONTAINERBUILD1_URL}
      IMAGE_CONTAINERBUILD1_VERSAO: ${IMAGE_CONTAINERBUILD1_VERSAO}
      IMAGE_CONTAINERBUILD1_CERT: ${IMAGE_CONTAINERBUILD1_CERT}
      IMAGE_CONTAINERBUILD1_CERTKEY: ${IMAGE_CONTAINERBUILD1_CERTKEY}
      IMAGE_CONTAINERBUILD1_CERTDIR: ${IMAGE_CONTAINERBUILD1_CERTDIR}